/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Show_Student_Data.java
 *
 * Created on Jul 9, 2015, 9:55:22 AM
 */

package project_cod_ip;
 import java.sql.* ;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Devesh
 */
public class Show_Student_Data extends javax.swing.JFrame {


    /** Creates new form Show_Student_Data */
    public Show_Student_Data() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Scholar Id", "Name", "Class", "Section", "Stream", "Father's Name", "Mother's Name", "Mobile Number", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Scholar Number");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("All Data");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cts" , "root" , "mysql");
        Statement stmt = con.createStatement();
        int schid = Integer.parseInt(JOptionPane.showInputDialog("Enter Scholar Id"));
        String s = "select * from Student where s_id = "+schid+" " ;
        ResultSet rs = stmt.executeQuery(s);

        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        int c=m.getRowCount();
             for (int i=0;i<c;i++)
         m.removeRow(0);
        if(rs.next())
        {

        String name = rs.getString("Name");
        int clss = rs.getInt("Class");
        String sect = rs.getString("Section");
        String stream = rs.getString("Stream");
        String F_Name = rs.getString("F_Name");
        String M_Name = rs.getString("M_Name");
        long m_num = rs.getLong("M_Num");
        String add = rs.getString("Address");

        m.addRow(new Object[]{schid,name,clss,sect,stream,F_Name,M_Name,m_num,add});

        }
        jTable1.setModel(m);

        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cts" , "root" , "mysql");
        Statement stmt = con.createStatement();
        String s = "select * from Student" ;
        ResultSet rs = stmt.executeQuery(s);
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        int c=m.getRowCount();
             for (int i=0;i<c;i++)
         m.removeRow(0);
        while(rs.next())
        {
        int schid =rs.getInt("S_Id") ;
        String name = rs.getString("Name");
        int clss = rs.getInt("Class");
        String sect = rs.getString("Section");
        String stream = rs.getString("Stream");
        String F_Name = rs.getString("F_Name");
        String M_Name = rs.getString("M_Name");
        long m_num = rs.getLong("M_Num");
        String add = rs.getString("Address");

        m.addRow(new Object[]{schid,name,clss,sect,stream,F_Name,M_Name,m_num,add});

        }
        jTable1.setModel(m);

        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new cod().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_Student_Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
